1
htmlacademy-htmlcss/834003-gllacy-30 pull request #2
Opened 2021-01-21 20:06 UTC by Ruslis80

2021-01-22 20:01 UTC, Ruslis80 commented
Делаю что могу

2021-01-25 06:06 UTC, Dima-Dim requested changes
По заданию нужно сделать разметку главной страницы, без стилей и без изображений. В первую очередь это говорит о том, что у Вас на данный момент информации о том, как делать правильно всё остальное. В результате не учтены критерии https://up.htmlacademy.ru/htmlcss/30/criteries#b14 и 
https://up.htmlacademy.ru/htmlcss/30/criteries#b16.
Если делаешь что-то вперёд читай внимательно ТЗ, Критерии и Стайлгайд. В таком случае можно понять как правильно двигаться к цели.

2021-01-25 06:06 UTC, Dima-Dim commented on index.html
> +            <input type="button" value="Отправить">
Не нужно использовать инпут для кнопок. Для отправки форму у нас есть соответствующий тег.

2021-01-25 06:06 UTC, Dima-Dim commented on index.html
> +             8 812 450-25-25<br>
https://up.htmlacademy.ru/htmlcss/30/criteries#d29

2021-01-25 06:06 UTC, Dima-Dim commented on index.html
> +         <section>
Этот контейнер точно нужен?

2021-01-25 06:06 UTC, Dima-Dim commented on index.html
> +         <section>
Этот тоже нужен?

2021-01-25 06:06 UTC, Dima-Dim commented on index.html
> +                     <img src="img/icons/heart.png" width="15" height="13" alt="Сердце"> Для поставщиков
Это не контентное изображение.

2021-01-25 06:06 UTC, Dima-Dim commented on index.html
> +                 <p>
Для чего нам тут p?

2021-01-25 06:06 UTC, Dima-Dim commented on index.html
> +           <ul>
Это не похоже на список.

2021-01-29 06:32 UTC, Dima-Dim reviewed
Оставшиеся правки можешь внести в следующем задании.

2021-01-29 06:32 UTC, Dima-Dim commented on catalog.html
> +                <p>8 812 450-25-25</p>
https://up.htmlacademy.ru/htmlcss/30/criteries#d29

2021-01-29 06:32 UTC, Dima-Dim commented on catalog.html
> +                <div>
Нам точно будут нужны контейнеры вокруг списков?

2021-01-29 06:32 UTC, merged