Закончил четвёртое задание
htmlacademy-htmlcss/834003-gllacy-30 pull request #4
Opened 2021-02-02 10:29 UTC by Ruslis80

2021-02-03 16:16 UTC, Dima-Dim requested changes
Обратить внимание на названия файлов.

2021-02-03 16:16 UTC, Dima-Dim commented on catalog.html
> +          <img src="img/svg/Лого.svg" width="154" height="64" alt="Логотип магазина">
https://up.htmlacademy.ru/htmlcss/30/criteries#b14
`использованы только латинские символы`

2021-02-03 16:16 UTC, Dima-Dim commented on css/style.css
> +  height: auto;
Это значение по умолчанию, прописывать его явно не обязательно.

2021-02-03 16:16 UTC, Dima-Dim commented on css/style.css
> +  height: 229px;
Подобное ограничение здесь и в других блоках с текстом приведёт к проблемам при переполнении. Об этом расскажут в `8. Оформление контента`.

2021-02-03 16:16 UTC, Dima-Dim commented on css/style.css
> +                    url(../img/мороженое/Хит\ 1.png);
Изображение мороженного контентное, не нужно делать его фоном.

2021-02-03 16:16 UTC, Dima-Dim commented on index.html
> +            <img src="img/мороженое/Мороженко1.png"  width="372" height="584"
Изображение в слайде лучше сделать одно, так будет проще и тебе верстать и контент менеджерам обслуживать проект :)

2021-02-03 16:16 UTC, Dima-Dim commented on index.html
> +          <figure class="gallery-content">
Не забудь про то, что слайдов несколько.

2021-02-03 16:16 UTC, Dima-Dim commented on index.html
> +          <p>
На данный момент непонятно для чего обёртки в виде тегов p.

2021-02-07 07:25 UTC, Dima-Dim requested changes
Разобраться с названиями классов.
Перестать фиксировать по высоте блоки с текстом.
Не использовать float-ы для построения сеток.
Вряд ли для body-fon.png png это подходящий формат.
На лекции Николай ведь говорил, что ice1.png не png?
Ещё не всё соответствует https://up.htmlacademy.ru/htmlcss/30/criteries#b14

2021-02-07 07:25 UTC, Dima-Dim commented on css/style.css
> +.item {
Что `item`? :) Не лучшее имя для класса.

2021-02-07 07:25 UTC, Dima-Dim commented on css/style.css
> +  position: absolute;
Опасно для текста, скорее нет. Наблюдай за этим при дальнейшей стилизации.

2021-02-07 07:25 UTC, Dima-Dim commented on css/style.css
> +  position: absolute;
Тоже опасный момент.

2021-02-07 07:25 UTC, Dima-Dim commented on css/style.css
> +.tovar-list p {
Зачем тянуться от списка до контента элемента через элемент? Есть же, например, `items`.

2021-02-07 07:25 UTC, Dima-Dim commented on css/style.css
> +  position: absolute;
Тут, конечно, может и всё будет нормально, но, опять же, не желательно.

2021-02-07 07:25 UTC, Dima-Dim commented on css/style.css
> +  float: left;
Нет.
https://up.htmlacademy.ru/htmlcss/30/criteries#b7

2021-02-07 07:25 UTC, Dima-Dim commented on css/style.css
> +  height: 324px;
А если заголовок будет в 3 или 4 строки?

2021-02-07 07:25 UTC, Dima-Dim commented on css/style.css
> +  position: absolute;
Вот тут нормально :)

2021-02-07 07:25 UTC, Dima-Dim commented on css/style.css
> +.xit {
https://up.htmlacademy.ru/htmlcss/30/criteries#d21

2021-02-07 07:25 UTC, Dima-Dim commented on css/style.css
> +  clear: left;
Туда же куда и float.

2021-02-07 07:25 UTC, Dima-Dim commented on css/style.css
> +  height: 220px;
Тут у нас тоже текст статичный по высоте и менять мы его запретим?

2021-02-07 07:25 UTC, Dima-Dim commented on css/style.css
> +.adres {
Тоже нужно нормальное название.

2021-02-10 17:33 UTC, Ruslis80 commented
Английский надо учить наверное

2021-02-10 17:37 UTC, Dima-Dim commented
> Английский надо учить наверное

Пока не выучил можно пользоваться переводчиками, такими как https://translate.google.com

2021-02-10 17:38 UTC, Ruslis80 commented
а как теперь на проверку тебе отослать?

2021-02-11 07:06 UTC, Dima-Dim commented
> а как теперь на проверку тебе отослать?

Для этого нужно на странице выполняемого заданния, в интерфейсе Академии нажать соответствующую кнопку.

2021-02-11 07:15 UTC, Dima-Dim requested changes
https://up.htmlacademy.ru/htmlcss/30/criteries#b2
Почему у нас из 2? Который проверять? :)
Уточню, у нас должен быть один файл для всех страниц разрабатываемого сайта.

`img/Favicon/152.ico` - https://up.htmlacademy.ru/htmlcss/30/criteries#b14
`В названиях и расширениях файлов нет заглавных букв и пробелов, использованы только латинские символы`

`cart.png ` https://translate.google.com/?hl=ru&sl=en&tl=ru&text=cart&op=translate переводится как тележка/корзина :)
https://up.htmlacademy.ru/htmlcss/30/criteries#d21

2021-02-13 08:41 UTC, Ruslis80 commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
code
	{mso-style-priority:99;
	font-family:"Courier New";}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:2.0cm 42.5pt 2.0cm 3.0cm;}
div.WordSection1
	{page:WordSection1;}
-->Это получается один css на две страницы? Отправлено из приложения "Почта" для Windows 10 От: DimaОтправлено: 11 февраля 2021 г. в 9:16Кому: htmlacademy-htmlcss/834003-gllacy-30Копия: Руслан; ManualТема: Re: [htmlacademy-htmlcss/834003-gllacy-30] Графика всех страниц (#4) @Dima-Dim requested changes on this pull request.https://up.htmlacademy.ru/htmlcss/30/criteries#b2Почему у нас из 2? Который проверять? :)Уточню, у нас должен быть один файл для всех страниц разрабатываемого сайта.img/Favicon/152.ico - https://up.htmlacademy.ru/htmlcss/30/criteries#b14В названиях и расширениях файлов нет заглавных букв и пробелов, использованы только латинские символыcart.png https://translate.google.com/?hl=ru&sl=en&tl=ru&text=cart&op=translate переводится как тележка/корзина :)https://up.htmlacademy.ru/htmlcss/30/criteries#d21—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe. 

2021-02-13 16:11 UTC, Dima-Dim requested changes
Всё ещё два `css` файла
И неверные названия папок, например, `Favicon` и файлов, например `png/favicon 192.png` в `img`.

2021-02-14 17:19 UTC, Dima-Dim reviewed
Давай пойдём дальше. Замечания поправишь в рамках следующего задания.

2021-02-14 17:19 UTC, Dima-Dim commented on catalog.html
> +         <li><span>Сливочное</span></li>
А чего вдруг? Нормально же было. Ну да ладно, поправишь позже. И за одно предыдущий пункт это не пункт ни разу, потому что это просто декоративный разделитель.

2021-02-14 17:19 UTC, Dima-Dim commented on css/style.css
> +  height: 36px;
Сомнительная фиксация высоты.

2021-02-14 17:19 UTC, merged