Закончил графику начал стилизацию
htmlacademy-htmlcss/834003-gllacy-30 pull request #5
Opened 2021-02-17 17:35 UTC by Ruslis80

2021-02-19 06:58 UTC, Dima-Dim requested changes
Учесть https://up.htmlacademy.ru/htmlcss/30/criteries#d19

2021-02-19 06:58 UTC, Dima-Dim commented on css/style.css
> +  height: 48px;
Если текста будет сильно больше?

2021-02-19 06:58 UTC, Dima-Dim commented on css/style.css
> +  height: 402px;
Тоже вызовет проблемы с переполнением.

2021-02-19 06:58 UTC, Dima-Dim commented on css/style.css
> +table {
https://up.htmlacademy.ru/htmlcss/30/criteries#d25

2021-02-23 05:51 UTC, Dima-Dim commented on css/style.css
> +  outline: 5px solid rgba(255, 0, 0, 0.3);
https://up.htmlacademy.ru/htmlcss/30/criteries#d30

2021-02-23 05:51 UTC, merged

2021-02-23 07:43 UTC, Ruslis80 commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
pre
	{mso-style-priority:99;
	mso-style-link:"\0421\0442\0430\043D\0434\0430\0440\0442\043D\044B\0439 HTML \0417\043D\0430\043A";
	margin:0cm;
	font-size:10.0pt;
	font-family:"Courier New";}
span.HTML
	{mso-style-name:"\0421\0442\0430\043D\0434\0430\0440\0442\043D\044B\0439 HTML \0417\043D\0430\043A";
	mso-style-priority:99;
	mso-style-link:"\0421\0442\0430\043D\0434\0430\0440\0442\043D\044B\0439 HTML";
	font-family:"Courier New";}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:2.0cm 42.5pt 2.0cm 3.0cm;}
div.WordSection1
	{page:WordSection1;}
-->Это просто рамка что бы видно было, она потом уберётся. Отправлено из приложения "Почта" для Windows 10 От: DimaОтправлено: 23 февраля 2021 г. в 7:51Кому: htmlacademy-htmlcss/834003-gllacy-30Копия: Руслан; AuthorТема: Re: [htmlacademy-htmlcss/834003-gllacy-30] Стилизация главной страницы (#5) @Dima-Dim commented on this pull request.In css/style.css:>  }  img {   max-width: 100%;   height: auto; } +/* Main header */++.main-header {+  display: grid;+  min-width: 1200px;+  margin-bottom: 70px;+}++/* Main header logo */++.main-header-logo {+  outline: 5px solid rgba(255, 0, 0, 0.3);https://up.htmlacademy.ru/htmlcss/30/criteries#d30—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. 